version: '3'

services:
  router:
    restart: always
    image: 'nginx'
    ports:
      - 80:80
    volumes:
      - ./nginx_api_proxy.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - mcc
      - census
      - bookworm
  
  frontend:
    image: 'nginx'
    volumes:
      - './frontend/frontend:/var/www/html'
      - './frontend/nginx.conf:/etc/nginx/conf.d/default.conf'

  mcc:
    build:
      context: ./mcc
    command: '--root-path /api/mcc'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./test.env
  
  census:
    build:
      context: ./census
    command: '--root-path /api/census'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./test.env

  bookworm:
    build:
      context: ./bookworm
    command: '--root-path /api/bookworm'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./test.env
    ports: 
      - 8001:80
  
  db:
    image: postgres
    user: postgres
    env_file:
      - ./test.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
