version: '3'

services:
  router:
    image: 'nginx'
    ports:
      - 80:80
    volumes:
      - ./nginx_api_proxy.nginx:/etc/nginx/conf.d/default.conf
  
  frontend:
    build:
      context: ./frontend

  mcc:
    build:
      context: ./mcc
  
  census:
    build:
      context: ./census

  bookworm:
    build:
      context: ./bookworm
  
  db:
    image: postgres
    user: postgres
    env_file:
      - ./test.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
